name: Truffle DApp Build and Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '15.8.0'
    - name: Install npm 7.5.1
      run: npm install -g npm@7.5.1
    - name: Install Truffle
      run: npm install -g truffle@5.6.7
    - name: Install project dependencies
      run: npm install
    - name: Compile smart contracts
      run: truffle compile
    - name: Run tests (optional)
      run: truffle test
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: truffle-build
        path: build/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '15.8.0'
    - name: Install npm 7.5.1
      run: npm install -g npm@7.5.1
    - name: Install Truffle
      run: npm install -g truffle@5.6.7
    - name: Install project dependencies
      run: npm install
    - name: Compile contracts
      run: truffle compile
    - name: Deploy to network
      run: truffle migrate --network 
      # Optional: Use secrets for private keys or Infura
      env:
        MNEMONIC: ${{ secrets.MNEMONIC }}
        INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
